name: CI / Example Android

on:
  push:
    branches: [main, next]
    paths:
      - 'src/**'
      - 'android/**'
      - 'IapExample/android/**'
      - .github/ci-example-android.yml

  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - 'src/**'
      - 'android/**'
      - 'IapExample/android/**'
      - .github/ci-example-android.yml

jobs:
  build_android_example:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: "14.x"

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --immutable

      - name: Install dependencies for `IapExample/`
        run: yarn install --immutable
        working-directory: IapExample

      - name: Setup kernel for react native, increase watchers
        run: echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p

      - name: Grant execute permission for gradlew in example app
        run: chmod +x ./gradlew
        working-directory: IapExample/android

      - name: Build with example app with Gradle
        run: ./gradlew build test
        working-directory: IapExample/android

      - name: Unit tests results
        uses: actions/upload-artifact@v3
        with:
          name: play-unit-tests-results
          path: IapExample/android/build/reports/tests/testPlayDebugUnitTest/index.html
