name: CI Example

on:
  push:
    branches: [main]
    paths:
      - 'IapExample/android/**'
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build_android_example:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup kernel for react native, increase watchers
        run: echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p
      - name: Set up JDK 11.0.3
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: 11.0.3
      - name: Install base modules
        run: yarn; yarn build
      - name: Install modules
        run: cd IapExample;yarn
      - name: Grant execute permission for gradlew in example app
        run: chmod +x IapExample/android/gradlew
      - name: Build with example app with Gradle
        run: cd IapExample/android;./gradlew build test
