name: Publish main package

on:
  release:
    types: [created]

jobs:
  deploy:
    if: '!github.event.release.prerelease'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          cache: 'yarn'
          registry-url: 'https://registry.npmjs.org'

      - name: Remove example code
        run: rm -rf IapExample

      - name: Install dependencies
        run: yarn install --immutable

      - name: Run lint scripts
        run: yarn lint:ci

      - name: Verify no files have changed after auto-fix
        run: git diff -- ":(exclude)IapExample/*" --exit-code HEAD

      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
